### ISSUE TITLE
Please add dependency of fluentd 0.12

### ISSUE THREAD

**Issue by azrle** [tagomoris/fluent-plugin-ping-message#14]
@okkez @tagomoris 
According to https://github.com/tagomoris/fluent-plugin-ping-message/commit/046aa24960516c2188ecd62e61de7f3d6739bc39, `router.emit` will be called instead of `Fluent::Engine.emit`.

However, `router.emit` is introduced from `0.12.0`. Hence, IMHO, it is not compatible to fluentd version before `0.12.0`. Please add this dependency to the spec.

Thanks.

**Comment by tagomoris** [comment]
This code defines `router` method dynamically on Fluentd v0.10, so the latest version runs even on v0.10.x.
